/**
 * Tudo que a auditoria pode mostrar, traduzido. As chaves vêm de duas fontes: os literais
 * `entityType`/`action` gravados em `recordAudit()` pelo código atual, e os registros
 * históricos do banco de produção com nomes de uma versão anterior (ex.: `patient.deactivate`,
 * `procedure.activate`) — auditoria é histórico, e um registro de 2025 não pode aparecer em
 * inglês só porque a ação que o gerou já não existe mais no código.
 */
export const ACTION_LABELS: Record<string, string> = {
  "appointment.cancel": "Agendamento cancelado",
  "appointment.check_in": "Check-in",
  "appointment.complete": "Atendimento concluído",
  "appointment.confirm": "Agendamento confirmado",
  "appointment.create": "Agendamento criado",
  "appointment.delete": "Agendamento excluído",
  "appointment.no_show": "Falta registrada",
  "appointment.reschedule": "Agendamento reagendado",
  "automation.save": "Automação salva",
  "availability.create": "Disponibilidade criada",
  "availability.delete": "Disponibilidade removida",
  "billing.guide.attachment.download": "Anexo da guia baixado",
  "billing.guide.attachment.share": "Anexo da guia compartilhado",
  "billing.guide.attachment.view": "Anexo da guia visualizado",
  "billing.guide.cancel": "Guia cancelada",
  "billing.guide.email": "Guia enviada por e-mail",
  "billing.guide.issue": "Guia emitida",
  "billing.insurer.create": "Convênio cadastrado",
  "billing.insurer.update": "Convênio atualizado",
  "campaign.create": "Campanha criada",
  "campaign.dispatch": "Campanha disparada",
  "chat.retract": "Mensagem retraída",
  "document.issue": "Documento emitido",
  "financial.cancel": "Lançamento cancelado",
  "financial.create_receita": "Receita lançada",
  "financial.edit_amount": "Valor alterado",
  "financial.register_payment": "Pagamento registrado",
  logout: "Saída do sistema",
  "medical_record.add_diagnosis": "Diagnóstico adicionado",
  "medical_record.remove_diagnosis": "Diagnóstico removido",
  "medical_record.update": "Prontuário atualizado",
  "message.send": "Mensagem enviada",
  "message_template.create": "Modelo de mensagem criado",
  "message_template.update": "Modelo de mensagem atualizado",
  "package.catalog.activate": "Pacote ativado",
  "package.catalog.create": "Pacote criado",
  "package.catalog.reprocess": "Pacote reprocessado",
  "package.catalog.update": "Pacote atualizado",
  "package.link_appointment": "Sessão vinculada",
  "package.retroactive_link": "Vínculo retroativo",
  "package.sell": "Pacote vendido",
  pairing_code_requested: "Código de pareamento solicitado",
  "patient.clinical_info.update": "Info clínica atualizada",
  "patient.create": "Paciente cadastrado",
  "patient.deactivate": "Paciente inativado",
  "patient.update": "Paciente atualizado",
  "permission.user_override": "Permissão alterada",
  "prescription.issue": "Receituário emitido",
  "procedure.activate": "Procedimento ativado",
  "procedure.create": "Procedimento criado",
  "procedure.deactivate": "Procedimento inativado",
  "procedure.update": "Procedimento atualizado",
  "professional.create": "Profissional cadastrado",
  "professional.link": "Profissional vinculado",
  "professional.update": "Profissional atualizado",
  "profile.avatar_update": "Avatar atualizado",
  "profile.password_change": "Senha alterada",
  "profile.update": "Perfil atualizado",
  "queue.add_walk_in": "Encaixe na fila",
  "queue.call": "Paciente chamado",
  "queue.cancel": "Fila cancelada",
  "queue.release_to_queue": "Liberado para fila",
  "queue.transfer": "Transferido na fila",
  "room.create": "Sala criada",
  "sandbox.toggle": "Sandbox alternado",
  "schedule_exception.create": "Exceção de agenda criada",
  "schedule_exception.delete": "Exceção de agenda removida",
  "service.finish": "Atendimento finalizado",
  "service.pause": "Atendimento pausado",
  "service.resume": "Atendimento retomado",
  "service.start": "Atendimento iniciado",
  "settings.agenda_colors": "Cores da agenda",
  "settings.branding_update": "Identidade visual atualizada",
  "settings.integration_test": "Integração testada",
  "settings.integration_update": "Integração atualizada",
  "specialty.create": "Especialidade criada",
  "specialty.update": "Especialidade atualizada",
  "telehealth.call.end": "Teleconsulta encerrada",
  "telehealth.call.open": "Teleconsulta aberta",
  "telehealth.invite.create": "Convite de teleconsulta",
  "telehealth.limit.update": "Limite de teleconsulta atualizado",
  "user.deactivate": "Usuário inativado",
  "user.invite": "Usuário convidado",
  "user.password_reset_sent": "Reset de senha enviado",
  "user.role_change": "Papel alterado",
  "user.update": "Usuário atualizado",
}

export const ENTITY_LABELS: Record<string, string> = {
  appointment: "Agendamento",
  clinic: "Clínica",
  clinic_membership: "Vínculo de usuário",
  clinic_settings: "Configurações",
  clinical_document: "Documento clínico",
  conversation: "Conversa",
  financial_transaction: "Financeiro",
  insurer: "Convênio",
  internal_message: "Mensagem interna",
  medical_record: "Prontuário",
  message: "Mensagem",
  message_automation: "Automação de mensagem",
  message_campaign: "Campanha",
  message_template: "Modelo de mensagem",
  patient: "Paciente",
  patient_package: "Pacote do paciente",
  prescription: "Receituário",
  procedure: "Procedimento",
  professional: "Profissional",
  professional_availability: "Disponibilidade",
  profile: "Perfil",
  queue_entry: "Fila",
  role: "Papel",
  room: "Sala",
  schedule_exception: "Exceção de agenda",
  service_guide: "Guia",
  service_session: "Atendimento",
  session_package: "Pacote",
  specialty: "Especialidade",
  video_call: "Teleconsulta",
}

/**
 * Rede de segurança para um slug que nenhum dos dois mapas acima cobre — melhor "Foo Bar"
 * do que "foo.bar_baz" cru na tela. Não é tradução, é só não mostrar pontuação de código.
 */
export function humanizeSlug(slug: string): string {
  const spaced = slug.replace(/[._]/g, " ").trim()
  return spaced.charAt(0).toUpperCase() + spaced.slice(1)
}

/**
 * Nomes dos campos que aparecem em "O que mudou" — são as chaves do JSON gravado por
 * `recordAudit()`, escritas em inglês porque são nomes de variável do código, não texto de
 * tela. Cobre os campos mais comuns; o que não estiver aqui cai em `humanizeField`.
 */
export const FIELD_LABELS: Record<string, string> = {
  enabled: "Ativado",
  base_url: "Servidor",
  baseUrl: "Servidor",
  path: "Caminho",
  webhook_url: "URL do webhook",
  webhookUrl: "URL do webhook",
  secret: "Chave secreta",
  secretChanged: "Chave alterada",
  channels: "Canais",
  integration: "Integração",
  httpStatus: "Status HTTP",
  logo_url: "Logo",
  amount: "Valor",
  payment_method_id: "Forma de pagamento",
  notes: "Observações",
  chargeStatus: "Situação da cobrança",
  status: "Situação",
  granted: "Concedida",
  sandbox: "Sandbox",
  full_name: "Nome completo",
  email: "E-mail",
  role_id: "Papel",
  role: "Papel",
  clinic_id: "Clínica",
  patient_id: "Paciente",
  professional_id: "Profissional",
  procedure_id: "Procedimento",
  specialty_id: "Especialidade",
  active: "Ativo",
  active_ate: "Ativo até",
  phone: "Telefone",
  cpf: "CPF",
  birth_date: "Data de nascimento",
  reason: "Motivo",
  total_sessions: "Total de sessões",
  sessions_used: "Sessões usadas",
  total_price: "Valor total",
  price: "Preço",
  duration_minutes: "Duração (min)",
  start_time: "Início",
  end_time: "Fim",
  color: "Cor",
  title: "Título",
  body: "Texto",
  subject: "Assunto",
  type: "Tipo",
  cid: "CID",
  quantity: "Quantidade",
}

/** Fallback para uma chave sem tradução: separa camelCase e underscore em palavras. */
export function humanizeField(key: string): string {
  if (FIELD_LABELS[key]) return FIELD_LABELS[key]
  const spaced = key.replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/_/g, " ")
  return spaced.charAt(0).toUpperCase() + spaced.slice(1).toLowerCase()
}
