export const ACTION_LABELS: Record<string, string> = {
  "appointment.create": "Agendamento criado",
  "appointment.cancel": "Agendamento cancelado",
  "appointment.confirm": "Agendamento confirmado",
  "appointment.reschedule": "Agendamento reagendado",
  "appointment.check_in": "Check-in",
  "appointment.complete": "Atendimento concluído",
  "appointment.delete": "Agendamento excluído",
  "appointment.no_show": "Falta registrada",
  "patient.create": "Paciente cadastrado",
  "patient.update": "Paciente atualizado",
  "patient.clinical_info.update": "Info clínica atualizada",
  "financial.register_payment": "Pagamento registrado",
  "financial.cancel": "Lançamento cancelado",
  "financial.edit_amount": "Valor alterado",
  "service.start": "Atendimento iniciado",
  "service.finish": "Atendimento finalizado",
  "service.pause": "Atendimento pausado",
  "service.resume": "Atendimento retomado",
  "queue.call": "Paciente chamado",
  "queue.add_walk_in": "Encaixe na fila",
  "queue.cancel": "Fila cancelada",
  "queue.release_to_queue": "Liberado para fila",
  "queue.transfer": "Transferido na fila",
  "document.issue": "Documento emitido",
  "prescription.issue": "Receituário emitido",
  "medical_record.update": "Prontuário atualizado",
  "medical_record.add_diagnosis": "Diagnóstico adicionado",
  "medical_record.remove_diagnosis": "Diagnóstico removido",
  "message.send": "Mensagem enviada",
  "message_template.create": "Template criado",
  "message_template.update": "Template atualizado",
  "automation.save": "Automação salva",
  "campaign.create": "Campanha criada",
  "campaign.dispatch": "Campanha disparada",
  "chat.retract": "Mensagem retraída",
  "user.invite": "Usuário convidado",
  "user.role_change": "Papel alterado",
  "user.update": "Usuário atualizado",
  "user.password_reset_sent": "Reset de senha enviado",
  "permission.user_override": "Permissão alterada",
  "settings.branding_update": "Identidade visual",
  "settings.integration_update": "Integração atualizada",
  "settings.integration_test": "Integração testada",
  "settings.agenda_colors": "Cores da agenda",
  "profile.update": "Perfil atualizado",
  "profile.avatar_update": "Avatar atualizado",
  "profile.password_change": "Senha alterada",
  "procedure.create": "Procedimento criado",
  "procedure.update": "Procedimento atualizado",
  "professional.create": "Profissional cadastrado",
  "professional.update": "Profissional atualizado",
  "professional.link": "Profissional vinculado",
  "specialty.create": "Especialidade criada",
  "specialty.update": "Especialidade atualizada",
  "package.catalog.create": "Pacote criado",
  "package.catalog.update": "Pacote atualizado",
  "package.sell": "Pacote vendido",
  "package.link_appointment": "Sessão vinculada",
  "package.retroactive_link": "Vínculo retroativo",
  "billing.insurer.create": "Convênio cadastrado",
  "billing.insurer.update": "Convênio atualizado",
  "billing.guide.issue": "Guia emitida",
  "billing.guide.cancel": "Guia cancelada",
  "billing.guide.email": "Guia enviada por e-mail",
  "telehealth.call.open": "Teleconsulta aberta",
  "telehealth.call.end": "Teleconsulta encerrada",
  "telehealth.invite.create": "Convite de teleconsulta",
  "availability.create": "Disponibilidade criada",
  "availability.delete": "Disponibilidade removida",
  "schedule_exception.create": "Exceção de agenda criada",
  "schedule_exception.delete": "Exceção de agenda removida",
  "room.create": "Sala criada",
  logout: "Logout",
  "sandbox.toggle": "Sandbox alternado",
}

export const ENTITY_LABELS: Record<string, string> = {
  appointment: "Agendamento",
  patient: "Paciente",
  financial_transaction: "Financeiro",
  queue_entry: "Fila",
  service_session: "Atendimento",
  document: "Documento",
  prescription: "Receituário",
  medical_record: "Prontuário",
  message: "Mensagem",
  user: "Usuário",
  profile: "Perfil",
  clinic: "Clínica",
  clinic_settings: "Configurações",
  procedure: "Procedimento",
  professional: "Profissional",
  specialty: "Especialidade",
  session_package: "Pacote",
  patient_package: "Pacote do paciente",
  insurer: "Convênio",
  guide: "Guia",
  telehealth_call: "Teleconsulta",
  availability_rule: "Disponibilidade",
  schedule_exception: "Exceção",
  room: "Sala",
  campaign: "Campanha",
  message_template: "Template",
  message_automation: "Automação",
  role_permission: "Permissão",
}
